# Generated by Django 5.2.17 on 2026-09-30 06:08

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=253, unique=True)),
                ('industry', models.CharField(blank=True, max_length=200)),
                ('summary', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('api', 'API'), ('import', 'Import')], default='api', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('qualified', 'Qualified'), ('needs_review', 'Needs review'), ('not_a_fit', 'Not a fit'), ('contacted', 'Contacted'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=20)),
                ('fit_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('need', models.TextField(blank=True)),
                ('suggested_reply', models.TextField(blank=True)),
                ('qualification', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('qualification_error', models.CharField(blank=True, max_length=500)),
                ('qualified_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='crm.company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.contact')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('note', 'Note'), ('email', 'Email'), ('call', 'Call'), ('meeting', 'Meeting')], max_length=20)),
                ('body', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.lead')),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoreEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('n8n_mcp', 'n8n MCP'), ('import', 'Import')], max_length=20)),
                ('fit_score', models.PositiveSmallIntegerField()),
                ('suggested_status', models.CharField(choices=[('new', 'New'), ('qualified', 'Qualified'), ('needs_review', 'Needs review'), ('not_a_fit', 'Not a fit'), ('contacted', 'Contacted'), ('won', 'Won'), ('lost', 'Lost')], max_length=20)),
                ('raw', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_events', to='crm.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='contact_email_ci_unique'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', '-created_at'], name='lead_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(condition=models.Q(('qualification', 'pending')), fields=['qualification'], name='lead_qualification_pending_idx'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(condition=models.Q(('fit_score__isnull', True), ('fit_score__lte', 100), _connector='OR'), name='lead_fit_score_0_100'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['lead', '-occurred_at'], name='activity_lead_time_idx'),
        ),
        migrations.AddIndex(
            model_name='scoreevent',
            index=models.Index(fields=['lead', '-created_at'], name='score_event_lead_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='scoreevent',
            constraint=models.CheckConstraint(condition=models.Q(('fit_score__lte', 100)), name='score_event_fit_score_0_100'),
        ),
    ]
