# Generated by Django 5.2.17 on 2026-09-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoreevent',
            options={'ordering': ['-created_at'], 'permissions': [('ingest_n8n_results', 'Can push n8n scoring results')]},
        ),
        migrations.AddField(
            model_name='scoreevent',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('api', 'API'), ('import', 'Import'), ('n8n', 'n8n')], default='api', max_length=20),
        ),
        migrations.AlterField(
            model_name='scoreevent',
            name='source',
            field=models.CharField(choices=[('n8n_mcp', 'n8n MCP'), ('n8n_push', 'n8n push'), ('import', 'Import')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='scoreevent',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('external_id',), name='score_event_external_id_unique'),
        ),
    ]
